### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by obligated** [dekujs/todomvc#2]
Ran into this issue when calling `npm start`

```
~/todomvc/client/todos/data.js:15
f (typeof superClass !== 'function' && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object
    at _inherits (/home/felix/todomvc/client/todos/data.js:15:113)
    at /home/felix/todomvc/client/todos/data.js:18:4
    at Object.<anonymous> (/home/felix/todomvc/client/todos/data.js:13:27)
    at Module._compile (module.js:456:26)
    at normalLoader (/home/felix/todomvc/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:150:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/felix/todomvc/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:163:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by dominicbarnes** [comment]
What version of node are you running?

**Comment by obligated** [comment]
1.4.28

**Comment by dominicbarnes** [comment]
That's not a real version of either node or iojs? Is that possibly the version of npm?

**Comment by dominicbarnes** [comment]
It looks like you might be using node 0.10 (which has npm@1.4.28 bundled)

node 0.10 is not supported, please upgrade to either node 0.12 or iojs.

**Comment by dominicbarnes** [comment]
If you are able to figure out why this particular code doesn't work on node 0.10, (despite being transpiled by babel) PRs are welcome. But since node 0.12 is the current stable version, that's what we will support.

Thanks! :D

**Comment by obligated** [comment]
Alright, I'll check my version again. Thanks!
